# fly.toml app configuration file generated for gobarchar on 2024-01-05T13:57:22+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "gobarchar"
primary_region = "ams"

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["gcr.io/paketo-buildpacks/go"]

[build.args]
  BP_GO_TARGETS = "./cmd/gobarchar"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 2
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
