name: test

on:
  push:
    branches:
      - '*'
    paths:
      - '**.go'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.19.1'

      - name: Run tests
        run: go test -v -cover -timeout=30s ./...
